### ISSUE TITLE
Mobile friendly frontend

### ISSUE THREAD

**Issue by mrbrianevans** [mrbrianevans/number-format-converter#27]
Make the client side display well on mobile phones

**Comment by jgsheppa** [comment]
I think I can handle this one if you want.

**Comment by mrbrianevans** [comment]
Hi James,

That would be excellent if you could help out!

I've already created a branch for this issue called [`mobile-design`](https://github.com/mrbrianevans/number-format-converter/tree/mobile-design), so checkout that branch. I'm not sure exactly how it works, if you are able to pull request to that branch, and then if it will show up in the pull request I've opened. If not, I will close my pull request, and then you can open one directly to the master.

**Comment by jgsheppa** [comment]
Hey @mrbrianevans, the mobile view is looking a lot better, but let me know if there's anything else I can adjust. 

I also thought it might look nice to replace "Our repository" with the github logo. If you don't like it, I can change it back, but I thought the logo might look nice. 

I had trouble switching onto your branch, so I pushed from a branch I made. Not sure what the problem was.

Cheers,

James

**Comment by mrbrianevans** [comment]
Okay, I've created a new pull request from your branch to mine. GitHub logo in footer sounds good!

**Comment by mrbrianevans** [comment]
Hey @jgsheppa , just had a look, and its looking good! 
There was just one issue which is `flex-direction: row-reverse` in `footer.css` was causing the dropdowns and textareas to flip position, so I removed that. Otherwise, all good, I'm merging to master.
